# version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database", "--quiet"]
      interval: 3s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8088:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin     

  backend:
    container_name: backend
    image: zali1813/avaprodetailing_backend:v1
    restart: always
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  bot:
    container_name: bot
    image: zali1813/avaprodetailing_bot:v1
    restart: always
    env_file:
      - ./.env

volumes:
  postgres_data:
  pgadmin_data: