"""Add history models for each main models and make relationships between them.

Revision ID: 0a17ab2ba466
Revises: 294f07522dd8
Create Date: 2024-04-12 18:29:07.266244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a17ab2ba466'
down_revision: Union[str, None] = '294f07522dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalitysettingshistory',
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('old_data', sa.String(length=255), nullable=False),
    sa.Column('new_data', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], name='fk_loyalitysettingshistory_changed_by_id_user'),
    sa.ForeignKeyConstraint(['object_id'], ['loyalitysettings.id'], name='fk_loyalitysettingshistory_object_id_loyalitysettings'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userhistory',
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('old_data', sa.String(length=255), nullable=False),
    sa.Column('new_data', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], name='fk_userhistory_changed_by_id_user'),
    sa.ForeignKeyConstraint(['object_id'], ['user.id'], name='fk_userhistory_object_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carhistory',
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('old_data', sa.String(length=255), nullable=False),
    sa.Column('new_data', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['user.id'], name='fk_carhistory_changed_by_id_user', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['car.id'], name='fk_carhistory_car_id_car', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalityhistory',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('new_data', sa.String(length=255), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('loyality_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name='fk_loyalityhistory_admin_id_user'),
    sa.ForeignKeyConstraint(['loyality_id'], ['loyality.id'], name='fk_loyalityhistory_loyality_id_loyality'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_loyalityhistory_user_id_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('user', sa.INTEGER(), nullable=False),
    sa.Column('table', sa.VARCHAR(length=255), nullable=False),
    sa.Column('comment', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loyalityhistory')
    op.drop_table('carhistory')
    op.drop_table('userhistory')
    op.drop_table('loyalitysettingshistory')
    # ### end Alembic commands ###
