"""fixed_loyality

Revision ID: 5b10c90bc6bd
Revises: bafa60a0ef4e
Create Date: 2024-04-10 12:53:21.568422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b10c90bc6bd'
down_revision: Union[str, None] = 'bafa60a0ef4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
