"""Add relationship between User and Loyality models.

Revision ID: fdc9630eae93
Revises: d1e311cc96d4
Create Date: 2024-04-12 23:00:13.218002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc9630eae93'
down_revision: Union[str, None] = 'd1e311cc96d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
